/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class ContactIcons {
  ContactIcons._();

  static const _kFontFam = 'contact_icons';
  static const _kFontPkg = null;

  static const IconData email =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium =
      IconData(0xf23a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xf318, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      IconData(0xf339, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
